<?php
/**
 * Created by PhpStorm.
 * User: minhngoc
 * Date: 23/08/2019
 * Time: 09:44
 */
return [
    'mysql'=>[
        'address'=>[
            'id'=>[
                'type'=>'int',
                'column'=>'add_id'
            ],
            'type'=>[
                'type'=>'string',
                'column'=>'add_type',
                'values'=>[
                    'city',
                    'district',
                    'ward',
                    'street'
                ]
            ],
            'citid'=>[
                'type'=>'int',
                'column'=>'add_citid'
            ],
            'disid'=>[
                'type'=>'int',
                'column'=>'add_disid'
            ],
            'wardid'=>[
                'type'=>'int',
                'column'=>'add_wardid'
            ],
            'parent_id'=>[
                'type'=>'int',
                'column'=>'add_parent_id'
            ],
            'loc_id'=>[
                'type'=>'int',
                'column'=>'add_loc_id'
            ],
            'status' =>[
                'type'=>'int',
                'column'=>'add_status'
            ]
        ],
        'location'=>[
            'id'=>[
                'type'=>'int',
                'column'=>'loc_id'
            ],
            'type'=>[
                'type'=>'string',
                'column'=>'loc_type',
                'values'=>[
                    'city',
                    'district',
                    'ward',
                    'street',
                    'project'
                ]
            ],
            'cit_id'=>[
                'type'=>'int',
                'column'=>'loc_cit_id'
            ],
            'dis_id'=>[
                'type'=>'int',
                'column'=>'loc_dis_id'
            ],
            'ward_id'=>[
                'type'=>'int',
                'column'=>'loc_ward_id'
            ],
            'street_id'=>[
                'type'=>'int',
                'column'=>'loc_street_id'
            ],
            'parent_id'=>[
                'type'=>'int',
                'column'=>'add_parent_id'
            ],
            'add_id'=>[
                'type'=>'int',
                'column'=>'loc_add_id'
            ],
            'citid'=>[
                'type'=>'int',
                'column'=>'loc_citid'
            ],
            'disid'=>[
                'type'=>'int',
                'column'=>'loc_disid'
            ],
            'wardid'=>[
                'type'=>'int',
                'column'=>'loc_wardid'
            ],
            'streetid'=>[
                'type'=>'int',
                'column'=>'loc_streetid'
            ],
            'rsync_address'=>[
                'type'=>'int',
                'column'=>'loc_rsync_address'
            ]
        ]
    ]
];