<?php
return array(
    'timezone' => 'Asia/Ho_Chi_Minh',
    'app_name' => env('APP_NAME', 'sosanhnha.com'),
    'api_domain' => env('API_DOMAIN', 'https://sosanhnha.com'),
    'docs_url' => env('DOCS_URL', 'http://apivatgia.com'),
    'secret_access_token' => env('SECRET_ACCESS_TOKEN'),
    'secret_form_template' => env('SECRET_FORM_TEMPLATE', 'RhJPZsryWPzdB1ncwT15'),
    'exp_token' => env('EXP_TOKEN', 31536000), //second time
    'key_hashid' => 'fjdsljjl3j4j23fdl',
    'thumbnail_default' => 'https://sosanhnha.com//assets/images/noimage.png',
    'elastic_username' => env('ELASTIC_USERNAME', ''),
    'elastic_password' => env('ELASTIC_PASSWORD', ''),
    'email_send_notification' => env('EMAIL_SEND_NOTIFICATION', 'ngocnm@vatgia.com'),
    'elastic_host' => env('ELASTIC_HOST', 'localhost'),
    'elastic_port' => env('ELASTIC_PORT', 9200),
    'mail_notification_admin' => env('MAIL_NOTIFICATION_ADMIN', 'donkihote2595@gmail.com'),
    'source_path' => env('APP_SOURCE_DOMAIN', 'localhost:8000'),
    'slug_user_theme' => env('SLUG_USER_THEME', 'https://sosanhnha.com/du-an/'),
    'domain_theme_page_html' => env('DOMAIN_THEME_PAGE_HTML','https://sosanhnha.com/duan'),
    'status_payment' => [
        0 => 'Đang thực hiện giao dịch',
        1 => 'Giao dịch chưa xác minh OTP',
        2 => 'Giao dịch đã xác minh OTP',
        4 => 'Giao dịch hoàn thành',
        5 => 'Giao dịch bị hủy',
        6 => 'Giao dịch bị từ chối nhận tiền',
        7 => 'Giao dịch hết hạn',
        8 => 'Giao dịch thất bại',
        12 => 'Giao dịch bị đóng băng',
        13 => 'Giao dịch bị tạm giữ (thanh toán an toàn)',
        15 => 'Giao dịch bị hủy khi chưa xác minh OTP',
        16 => 'Giao dịch chưa được xác minh.(giao dịch giả mạo)',
        17 => 'Tạm ứng'
    ],
    'order_type'=>[
        0 => "Không xác định",
        1 => "Momo QrCode",
        2 => "Bảo Kim QrCode",
        3 => "ATM Nội Địa",
        5 => "Master Card",
        6 => "UPVIP tin",
        7 => "Làm mới tin",
        8 => "Lấy liên hệ"
    ],
    'seo_theme_config' => [
//        'description' => 'Kênh so sánh, đánh giá số 1 về bất động sản, nội thất, thiết kế nhà tại Việt Nam: cho thuê nhà đất, văn phòng, căn hộ,mua bán nhà đất, biệt thự, chung cư. Các lĩnh vực liên quan đến bất động sản: xây dựng, nội thất, kiến trúc, ngoại thất, phong thuỷ, luật pháp, tư vấn.',
//        'og:description' => 'Kênh so sánh, đánh giá số 1 về bất động sản, nội thất, thiết kế nhà tại Việt Nam: cho thuê nhà đất, văn phòng, căn hộ,mua bán nhà đất, biệt thự, chung cư. Các lĩnh vực liên quan đến bất động sản: xây dựng, nội thất, kiến trúc, ngoại thất, phong thuỷ, luật pháp, tư vấn.',
//        'og:title' => 'So sánh nhà đất, chung cư | Mua bán nhà đất | Cho thuê nhà đất | So sánh chung cư | Định giá nhà đất',
//        'titel'=>'So sánh nhà đất, chung cư | Mua bán nhà đất | Cho thuê nhà đất | So sánh chung cư | Định giá nhà đất',
//        'og:image' => 'https://sosanhnha.com/assets/images/logo.png',
        'abstract' => 'Thông tin nhà đất, nội thất, thiết kế nhà, so sánh, đánh giá, bất động sản Việt Nam',
        'classification' => 'Thông tin nhà đất, nội thất, thiết kế nhà, so sánh, đánh giá, bất động sản Việt Nam',
        'area' => 'So sánh nhà đất, chung cư, nội thất, thiết kế nhà, giá cả chung cư và thị trường bất động sản',
        'copyright' => '©2017 sosanhnha.com',
        'owner' => 'sosanhnha.com',
        'generator' => 'BDS Group Jsc',
        'language' => 'Việt Nam ,vn',
//        'keywords' => 'nội, thất, bất, động, sản, so, sánh, đánh, giá,nhà,đất',
        'og:type' => 'website',
//        'og:url' => 'https://sosanhnha.com',
        'author'=>'sosanhnha.com',
        'article:section' => '',
        'article:tag' => 'Nhà đất, bất động sản, căn hộ, biệt thự',
        'geo:placename' => 'Việt Nam'
    ]
);